-- 001_status_events.sql
-- Purpose:
--   Create/align the `public.status` table for RTU device lifecycle events.
--
-- Firmware currently inserts:
--   device_id (text), event (text), uptime_ms (bigint),
--   sample_rate_ms (bigint), blink_on (boolean)
--
-- Optional field:
--   metadata (jsonb) for future event context from web/firmware.

begin;

create table if not exists public.status (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  device_id text not null,
  event text not null,
  uptime_ms bigint not null,
  sample_rate_ms bigint not null default 300000,
  blink_on boolean not null default false,
  metadata jsonb not null default '{}'::jsonb
);

-- If table existed before without metadata column, add it safely.
alter table public.status
  add column if not exists metadata jsonb not null default '{}'::jsonb;

alter table public.status
  add column if not exists sample_rate_ms bigint not null default 300000;

alter table public.status
  add column if not exists blink_on boolean not null default false;

-- Helpful indexes for dashboard/time-series queries.
create index if not exists idx_status_device_created_at
  on public.status (device_id, created_at desc);

create index if not exists idx_status_event_created_at
  on public.status (event, created_at desc);

-- Basic validation: avoid empty strings.
do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'status_device_id_nonempty'
      and conrelid = 'public.status'::regclass
  ) then
    alter table public.status
      add constraint status_device_id_nonempty check (length(trim(device_id)) > 0);
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'status_event_nonempty'
      and conrelid = 'public.status'::regclass
  ) then
    alter table public.status
      add constraint status_event_nonempty check (length(trim(event)) > 0);
  end if;
end $$;

-- RLS starter profile:
-- This is intentionally permissive for bring-up with anon/publishable key.
-- Tighten later to per-device identity policies (see NEXT_STEPS.md).
alter table public.status enable row level security;

drop policy if exists status_insert_anon on public.status;
create policy status_insert_anon
  on public.status
  for insert
  to anon, authenticated
  with check (true);

drop policy if exists status_select_anon on public.status;
create policy status_select_anon
  on public.status
  for select
  to anon, authenticated
  using (true);

commit;
